<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>MedCare Monthly Report - {{ $month }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #333; }
        h1 { text-align: center; color: #2563eb; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 13px; }
        th { background-color: #f1f5f9; color: #2563eb; }
        .summary { margin-top: 25px; font-size: 14px; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #555; }
    </style>
</head>
<body>
    <h1>MedCare Monthly Report</h1>
    <p><strong>Month:</strong> {{ $month }}</p>

    <div class="summary">
        <strong>Summary:</strong>
        <ul>
            <li>Total Appointments: {{ $total }}</li>
            <li>Approved: {{ $approved }}</li>
            <li>Pending: {{ $pending }}</li>
            <li>Declined: {{ $declined }}</li>
        </ul>
    </div>

    <table>
        <thead>
            <tr>
                <th>Student</th>
                <th>Date</th>
                <th>Status</th>
                <th>Reason</th>
            </tr>
        </thead>
        <tbody>
            @foreach($appointments as $a)
            <tr>
                <td>{{ $a->student_name ?? 'N/A' }}</td>
                <td>{{ \Carbon\Carbon::parse($a->requested_datetime)->format('M d, Y - h:i A') }}</td>
                <td>{{ ucfirst($a->status) }}</td>
                <td>{{ $a->reason ?? '—' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by MedCare System on {{ now()->format('F d, Y h:i A') }}
    </div>
</body>
</html>
